spring:
  application:
    name: Zego
  main:
    banner-mode: off
  shell:
    interactive:
      enabled: true

logging:
  level:
    root: ERROR
    navid.test.zego: ERROR

app:
  connection-timeout: 10000
  retry:
    max-attempts: 5
    interval: 2000
    max-interval: 5000
    back-off-multiplier: 2.0