name: zego-crawler
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - requests
  - beautifulsoup4
  - responses=0.24.0
  - lxml
  - pip:
      - tqdm
      - pytest
      - black
      - flake8