[tool.poetry]
name = "crawler"
version = "0.1.0"
description = "Zego take-home assessment"
authors = ["Alexey Shapovalov <alexshapovalov95@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
aiohttp = "^3.13"
beautifulsoup4 = "^4.14"
click = "^8.3"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0"
pytest-asyncio = "^1.3"

[tool.pytest.ini_options]
pythonpath = "crawler"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
